version: '3.8'

services:
  db:
    container_name: db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: new_schema
    ports:
      - "3307:3306"
    restart: always

  app:
    image: 'sha256:766f0e34fca5f42167ede6a01a2c40c8aca0e44d030fb5110b231d55bdc7bca8'
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db:3306/new_schema
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      - db
    restart: always